- name: Ensure the keyring directory exists
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Add Docker GPG key
  ansible.builtin.get_url:
    url: "{{docker_key_url}}"
    dest: /tmp/docker.gpg
    mode: '0644'
  
- name: Import Docker GPG key
  ansible.builtin.shell:
    cmd: gpg --dearmor -o {{docker_key_path}}< /tmp/docker.gpg
  args:
    creates: "{{docker_key_path}}"

- name: Set permissions for Docker GPG key
  ansible.builtin.file:
    path: "{{docker_key_path}}"
    mode: '0644'
    state: file

- name: Add Docker repository
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64 signed-by={{ docker_key_path }}] https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable"
    filename: docker
    state: present

- name: Update apt cache after adding Docker repository
  ansible.builtin.apt:
    update_cache: yes

- name: Install containerd.io
  ansible.builtin.apt:
    name: containerd.io
    state: present
