---
- name: Deploy kubernetes to cluster
  hosts: pve_cluster_1
  become: yes
  gather_facts: yes
  vars:
    k8s_gpg_key_url: https://pkgs.k8s.io/core:/stable:/v1.30/deb/Release.key
    k8s_apt_key_path: /etc/apt/keyrings/kubernetes-apt-keyring.gpg
    k8s_apt_repo: https://pkgs.k8s.io/core:/stable:/v1.30/deb
  roles:
    - k8s

# ubuntu
# curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.30/deb/Release.key | sudo gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
#  /etc/apt/keyrings/kubernetes-apt-keyring.gpg

# debian
# /etc/apt/trusted.gpg.d/kubernetes-apt-keyring.asc