---
- name: Deploy kubernetes to cluster
  hosts: pve_cluster_1
  become: yes
  gather_facts: yes
  vars:
    k8s_gpg_key_url: https://pkgs.k8s.io/core:/stable:/v1.29/deb/Release.key
    k8s_apt_key_path: /etc/apt/trusted.gpg.d/kubernetes-apt-keyring.asc
  roles:
    - k8s
