---
- name: Deploy kubernetes to cluster
  hosts: k8s
  become: yes
  gather_facts: yes
  vars:
    k8s_gpg_key_url: https://pkgs.k8s.io/core:/stable:/v1.30/deb/Release.key
    k8s_apt_key_path: /etc/apt/keyrings/kubernetes-apt-keyring.gpg
    k8s_apt_repo: https://pkgs.k8s.io/core:/stable:/v1.30/deb
    docker_key_url: https://download.docker.com/linux/debian/gpg
    docker_key_path: /etc/apt/keyrings/docker.gpg
    
  roles:
    - k8s